version: "3"
services:
  flask-app:
    build: .
    ports:
      - 11000:11000
    environment:
      - MONGO_DBNAME=Tasks
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - FLASK_APP=app.app:create_app
      - FLASK_ENV=development
      - FLASK_PORT=11000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: